function [p1,p2,p3,dp1,dp2,dp3] = autoGen_acrobot3Kinematics(q1,q2,q3,dq1,dq2,dq3,l1,l2,l3)
%AUTOGEN_ACROBOT3KINEMATICS
%    [P1,P2,P3,DP1,DP2,DP3] = AUTOGEN_ACROBOT3KINEMATICS(Q1,Q2,Q3,DQ1,DQ2,DQ3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Jan-2019 15:25:01

t2 = sin(q1);
t3 = l1.*t2;
t4 = q1+q2;
t5 = cos(q1);
t6 = l1.*t5;
p1 = [t3;t6];
if nargout > 1
    t7 = sin(t4);
    t8 = l2.*t7;
    t9 = cos(t4);
    t10 = l2.*t9;
    t11 = q1+q2+q3;
    t12 = t6+t10;
    t13 = t3+t8;
    p2 = [t13;t12];
end
if nargout > 2
    t14 = cos(t11);
    t15 = l3.*t14;
    t16 = t6+t10+t15;
    t17 = sin(t11);
    t18 = l3.*t17;
    t19 = t3+t8+t18;
    p3 = [t19;t16];
end
if nargout > 3
    dp1 = [dq1.*l1.*t5;-dq1.*l1.*t2];
end
if nargout > 4
    dp2 = [dq1.*t12+dq2.*l2.*t9;-dq1.*t13-dq2.*l2.*t7];
end
if nargout > 5
    dp3 = [dq2.*(t10+t15)+dq1.*t16+dq3.*l3.*t14;-dq2.*(t8+t18)-dq1.*t19-dq3.*l3.*t17];
end
