function [M11,M12,M13,M21,M22,M23,M31,M32,M33,f1,f2,f3] = autoGen_acrobot3Dynamics(q1,q2,q3,dq1,dq2,dq3,u1,u2,m1,m2,m3,g,l1,l2,l3)
%AUTOGEN_ACROBOT3DYNAMICS
%    [M11,M12,M13,M21,M22,M23,M31,M32,M33,F1,F2,F3] = AUTOGEN_ACROBOT3DYNAMICS(Q1,Q2,Q3,DQ1,DQ2,DQ3,U1,U2,M1,M2,M3,G,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Jan-2019 15:25:00

t3 = q1+q2;
t4 = cos(t3);
t5 = l2.*t4;
t6 = cos(q1);
t7 = l1.*t6;
t9 = q1+q2+q3;
t19 = cos(t9);
t20 = l3.*t19;
t2 = t5+t7+t20;
t8 = t5+t7;
t11 = sin(t3);
t12 = l2.*t11;
t13 = sin(q1);
t14 = l1.*t13;
t17 = sin(t9);
t18 = l3.*t17;
t10 = t12+t14+t18;
t15 = t12+t14;
t16 = l1.^2;
M11 = m3.*t2.^2+m2.*t8.^2+m3.*t10.^2+m2.*t15.^2+m1.*t6.^2.*t16+m1.*t13.^2.*t16;
if nargout > 1
    t21 = t12+t18;
    t22 = m3.*t10.*t21;
    t23 = t5+t20;
    t24 = m3.*t2.*t23;
    t25 = l2.*m2.*t4.*t8;
    t26 = l2.*m2.*t11.*t15;
    t27 = t22+t24+t25+t26;
    M12 = t27;
end
if nargout > 2
    t28 = l2.^2;
    t29 = l3.*m3.*t2.*t19;
    t30 = l3.*m3.*t10.*t17;
    t31 = t29+t30;
    M13 = t31;
end
if nargout > 3
    M21 = t27;
end
if nargout > 4
    M22 = m3.*t21.^2+m3.*t23.^2+m2.*t4.^2.*t28+m2.*t11.^2.*t28;
end
if nargout > 5
    t32 = l3.*m3.*t17.*t21;
    t33 = l3.*m3.*t19.*t23;
    t34 = t32+t33;
    M23 = t34;
end
if nargout > 6
    M31 = t31;
end
if nargout > 7
    M32 = t34;
end
if nargout > 8
    t35 = l3.^2;
    M33 = m3.*t17.^2.*t35+m3.*t19.^2.*t35;
end
if nargout > 9
    t36 = dq3.*l3.*t17;
    t37 = dq2.*t21;
    t38 = dq2.*l2.*t4;
    t39 = dq2.*l2.*t11;
    t40 = dq2.*t23;
    t41 = dq3.*l3.*t19;
    t42 = dq1.*t23;
    t43 = t40+t41+t42;
    t44 = dq2.*t43;
    t45 = dq1.*t2;
    t46 = t40+t41+t45;
    t47 = dq1.*t46;
    t48 = dq1.*l3.*t19;
    t49 = dq2.*l3.*t19;
    t50 = t41+t48+t49;
    t51 = dq3.*t50;
    t52 = t44+t47+t51;
    t53 = dq1.*l3.*t17;
    t54 = dq2.*l3.*t17;
    t55 = t36+t53+t54;
    t56 = dq3.*t55;
    t57 = dq1.*t10;
    t58 = t36+t37+t57;
    t59 = dq1.*t58;
    t60 = dq1.*t21;
    t61 = t36+t37+t60;
    t62 = dq2.*t61;
    t63 = t56+t59+t62;
    t64 = dq1.*t8;
    t65 = t38+t64;
    t66 = dq1.*t65;
    t67 = dq1.*l2.*t4;
    t68 = t38+t67;
    t69 = dq2.*t68;
    t70 = t66+t69;
    t71 = dq1.*t15;
    t72 = t39+t71;
    t73 = dq1.*t72;
    t74 = dq1.*l2.*t11;
    t75 = t39+t74;
    t76 = dq2.*t75;
    t77 = t73+t76;
    f1 = -g.*m3.*t10-g.*m2.*t15-m3.*t10.*t52+m3.*t2.*t63+m2.*t8.*t77-m2.*t15.*t70-g.*l1.*m1.*t13;
end
if nargout > 10
    f2 = -u1-g.*m3.*t21-m3.*t21.*t52+m3.*t23.*t63-g.*l2.*m2.*t11+l2.*m2.*t4.*t77-l2.*m2.*t11.*t70;
end
if nargout > 11
    f3 = -u2-g.*l3.*m3.*t17-l3.*m3.*t17.*t52+l3.*m3.*t19.*t63;
end
