% -------------------------------------------------------------------
%  Generated by MATLAB on 15-Jan-2019 14:50:42
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

ans = saveVarsMat.ans; % <1x1 function_handle> 不支持的类

clear saveVarsMat;
