function [p1,p2,p3,dp1,dp2,dp3] = autoGen_kinematics(q1,q2,q3,dq1,dq2,dq3,Lb,Ll,d)
%AUTOGEN_KINEMATICS
%    [P1,P2,P3,DP1,DP2,DP3] = AUTOGEN_KINEMATICS(Q1,Q2,Q3,DQ1,DQ2,DQ3,LB,LL,D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Jan-2019 11:13:48

t2 = sin(q1);
t3 = cos(q1);
t4 = Ll.*t3;
t5 = sin(q2);
t6 = cos(q2);
t7 = t4-d.*t3;
t8 = d.*t2;
p1 = [t8-Ll.*t2;t7];
if nargout > 1
    p2 = [-Ll.*t2+(Ll.*t5)./2.0;t4-(Ll.*t6)./2.0];
end
if nargout > 2
    t9 = cos(q3);
    t10 = sin(q3);
    p3 = [-Lb.*t5-Ll.*t2+d.*t10;t4+Lb.*t6-d.*t9];
end
if nargout > 3
    dp1 = [-dq1.*t7;dq1.*(t8-Ll.*t2)];
end
if nargout > 4
    dp2 = [-Ll.*dq1.*t3+(Ll.*dq2.*t6)./2.0;-Ll.*dq1.*t2+(Ll.*dq2.*t5)./2.0];
end
if nargout > 5
    dp3 = [-Lb.*dq2.*t6-Ll.*dq1.*t3+d.*dq3.*t9;-Lb.*dq2.*t5-Ll.*dq1.*t2+d.*dq3.*t10];
end
