function [A11,A12,A13,A21,A22,A23,A31,A32,A33,b1,b2,b3] = autoGen_heelStrike(q1,q2,q3,dq1,dq2,dq3,Mb,Ml,Lb,Ll,d,I,g)
%AUTOGEN_HEELSTRIKE
%    [A11,A12,A13,A21,A22,A23,A31,A32,A33,B1,B2,B3] = AUTOGEN_HEELSTRIKE(Q1,Q2,Q3,DQ1,DQ2,DQ3,MB,ML,LB,LL,D,I,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Jan-2019 10:18:48

t2 = cos(q3);
t7 = Ll.*t2;
t22 = d.*t2;
t3 = t7-t22;
t4 = sin(q3);
t6 = Ll.*t4;
t23 = d.*t4;
t5 = t6-t23;
t8 = sin(q2);
t9 = cos(q2);
t10 = Lb.*t8;
t11 = sin(q1);
t16 = d.*t11;
t12 = t6+t10-t16;
t13 = Lb.*t9;
t14 = cos(q1);
t17 = d.*t14;
t15 = t7+t13-t17;
A11 = -I-Ml.*t3.^2-Ml.*t5.^2-Ll.*Mb.*t2.*(t7-(Lb.*t9)./2.0)-Ll.*Mb.*t4.*(t6-(Lb.*t8)./2.0)-Ll.*Ml.*t4.*t12-Ll.*Ml.*t2.*t15;
if nargout > 1
    A12 = -I+(Lb.*Mb.*t8.*(t6-(Lb.*t8)./2.0))./2.0+(Lb.*Mb.*t9.*(t7-(Lb.*t9)./2.0))./2.0-Lb.*Ml.*t8.*t12-Lb.*Ml.*t9.*t15;
end
if nargout > 2
    A13 = -I+Ml.*d.*t11.*t12+Ml.*d.*t14.*t15;
end
if nargout > 3
    t18 = Lb.^2;
    t19 = t13-t17;
    t20 = t10-t16;
    A21 = -Ll.*Ml.*t2.*t19-Ll.*Ml.*t4.*t20+(Lb.*Ll.*Mb.*t2.*t9)./2.0+(Lb.*Ll.*Mb.*t4.*t8)./2.0;
end
if nargout > 4
    A22 = -I-(Mb.*t8.^2.*t18)./4.0-(Mb.*t9.^2.*t18)./4.0-Lb.*Ml.*t8.*t20-Lb.*Ml.*t9.*t19;
end
if nargout > 5
    A23 = -I+Ml.*d.*t11.*t20+Ml.*d.*t14.*t19;
end
if nargout > 6
    A31 = Ll.*Ml.*d.*t4.*t11+Ll.*Ml.*d.*t2.*t14;
end
if nargout > 7
    A32 = Lb.*Ml.*d.*t8.*t11+Lb.*Ml.*d.*t9.*t14;
end
if nargout > 8
    t21 = d.^2;
    A33 = -I-Ml.*t11.^2.*t21-Ml.*t14.^2.*t21;
end
if nargout > 9
    t24 = Ll.*dq1.*t14;
    t25 = t24-(Ll.*dq2.*t9)./2.0;
    t26 = (Ll.*t9)./2.0;
    t27 = Ll.*dq1.*t11;
    t28 = (Ll.*dq2.*t8)./2.0;
    t29 = (Ll.*t8)./2.0;
    t32 = Ll.*t14;
    t30 = t17-t32;
    t33 = Ll.*t11;
    t31 = t16-t33;
    b1 = -I.*dq1-I.*dq2-I.*dq3-Ml.*t3.*(t24+Lb.*dq2.*t9-d.*dq3.*t2)-Ml.*t5.*(t27+Lb.*dq2.*t8-d.*dq3.*t4)-Mb.*(t28-Ll.*dq1.*t11).*(-t6+t10+t29)+Mb.*t25.*(-t7+t13+t26)-Ml.*dq1.*t31.*(-t6+t10+t16)-Ml.*dq1.*t30.*(-t7+t13+t17);
end
if nargout > 10
    b2 = -I.*dq1-I.*dq2+Mb.*t25.*(t13+t26)+Mb.*(t10+t29).*(t27-t28)-Ml.*dq1.*t31.*(t10+t16)-Ml.*dq1.*t30.*(t13+t17);
end
if nargout > 11
    b3 = -I.*dq1-Ml.*d.*dq1.*t11.*t31-Ml.*d.*dq1.*t14.*t30;
end
