function [M11,M12,M13,M21,M22,M23,M31,M32,M33,f1,f2,f3] = autoGen_3lwalker_dynamics(q1,q2,q3,dq1,dq2,dq3,u1,u2,Mb,Ml,Lb,Ll,d,I,g)
%AUTOGEN_3LWALKER_DYNAMICS
%    [M11,M12,M13,M21,M22,M23,M31,M32,M33,F1,F2,F3] = AUTOGEN_3LWALKER_DYNAMICS(Q1,Q2,Q3,DQ1,DQ2,DQ3,U1,U2,MB,ML,LB,LL,D,I,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Jan-2019 10:18:44

t2 = cos(q1);
t7 = Ll.*t2;
t22 = d.*t2;
t3 = t7-t22;
t4 = sin(q1);
t6 = Ll.*t4;
t20 = d.*t4;
t5 = t6-t20;
t8 = sin(q2);
t9 = cos(q2);
t10 = Lb.*t8;
t11 = sin(q3);
t18 = d.*t11;
t12 = t6+t10-t18;
t21 = (Ll.*t9)./2.0;
t13 = t7-t21;
t23 = (Ll.*t8)./2.0;
t14 = t6-t23;
t15 = Lb.*t9;
t16 = cos(q3);
t19 = d.*t16;
t17 = t7+t15-t19;
M11 = -I-Ml.*t3.^2-Ml.*t5.^2-Ll.*Mb.*t2.*t13-Ll.*Mb.*t4.*t14-Ll.*Ml.*t4.*t12-Ll.*Ml.*t2.*t17;
if nargout > 1
    M12 = -I-Lb.*Ml.*t8.*t12+(Ll.*Mb.*t8.*t14)./2.0+(Ll.*Mb.*t9.*t13)./2.0-Lb.*Ml.*t9.*t17;
end
if nargout > 2
    M13 = -I+Ml.*d.*t11.*t12+Ml.*d.*t16.*t17;
end
if nargout > 3
    t24 = t10-t18+t20;
    t25 = t21-t22;
    t26 = t15-t19+t22;
    t27 = t10-t18+t23;
    t28 = t15-t19+t21;
    t29 = dq1.^2;
    t30 = dq2.^2;
    t31 = Ll.*t2.*t29;
    t32 = Ll.*t4.*t29;
    t33 = dq3.^2;
    t34 = t32-(Ll.*t8.*t30)./2.0;
    t35 = t31-(Ll.*t9.*t30)./2.0;
    t36 = Lb.*t8.*t30;
    t42 = d.*t11.*t33;
    t37 = t32+t36-t42;
    t38 = Lb.*t9.*t30;
    t41 = d.*t16.*t33;
    t39 = t31+t38-t41;
    t40 = t20-t23;
    M21 = Ll.*Mb.*t2.*t25-Ll.*Mb.*t4.*t40-Ll.*Ml.*t2.*t26-Ll.*Ml.*t4.*t24;
end
if nargout > 4
    M22 = -I-Lb.*Ml.*t8.*t24-(Ll.*Mb.*t9.*t25)./2.0-Lb.*Ml.*t9.*t26+(Ll.*Mb.*t8.*t40)./2.0;
end
if nargout > 5
    M23 = -I+Ml.*d.*t11.*t24+Ml.*d.*t16.*t26;
end
if nargout > 6
    M31 = -Ll.*Ml.*t2.*t28-Ll.*Ml.*t4.*t27;
end
if nargout > 7
    M32 = -Lb.*Ml.*t8.*t27-Lb.*Ml.*t9.*t28;
end
if nargout > 8
    M33 = -I+Ml.*d.*t11.*t27+Ml.*d.*t16.*t28;
end
if nargout > 9
    f1 = -Mb.*g.*t14-Ml.*g.*t5-Ml.*g.*t12-Mb.*t13.*t34+Mb.*t14.*t35+Ml.*t12.*t39-Ml.*t17.*t37;
end
if nargout > 10
    f2 = -u1-Mb.*g.*t40-Ml.*g.*t24+Mb.*t25.*t34+Mb.*t35.*t40+Ml.*t24.*t39-Ml.*t26.*t37;
end
if nargout > 11
    f3 = -u2-Ml.*g.*t27-Ml.*t28.*t37+Ml.*t27.*t39;
end
